Food_Stories/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('account.urls')),
    path('', include('story.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns +=  static(settings.STATIC_URL, document_root = settings.STATIC_ROOT) 
urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from .views import HomeView, about, contact

urlpatterns = [
    path('', HomeView.as_view(), name = 'home'),
    path('about/', about, name = 'about'),
    path('contact/', contact, name = 'contact')
]

story/urls.py
from django.urls import path
from .views import stories, CreateStoryView, RecipesView,SearchView,RecipesDetail

urlpatterns = [
    path('stories/', stories, name = 'stories'),
    # path('story/<int:pk>', story, name = 'story'),
    path('search/', SearchView.as_view(), name = 'blog_search'),
    path('create_story/', CreateStoryView.as_view(), name = 'create_story'),
    # path('create_recipe/', CreateRecipeView.as_view(), name = 'create_recipe'),
    path('recipes/', RecipesView.as_view(), name = 'recipes'),
    path('recipes/<int:pk>', RecipesDetail.as_view(), name = 'recipe'),
]

story/models.py
from django.db import models
from base.basemodel import BaseModel
from ckeditor_uploader.fields import RichTextUploadingField
from account.models import CustomUser
from django.urls import reverse
# Create your models here

class Tag(BaseModel):
    name=models.CharField(verbose_name="name of tag",max_length=20,help_text="Max 20 characters")
    def __str__(self):
        return self.name
    class Meta:
        verbose_name = "Tag"
        verbose_name_plural = "Tags"
class Author(BaseModel):
    name=models.CharField(verbose_name="name of author",max_length=20,help_text="Max 20 characters")
    def __str__(self):
        return self.name
    class Meta:
        verbose_name = "Author"
        verbose_name_plural = "Authors"

class Category(BaseModel):
    name = models.CharField(verbose_name="Name of Category",max_length=20,help_text="Max 20 characters")
    image = models.ImageField(verbose_name="Image of Category",upload_to="category_image")
    def __str__(self):
        return self.name
    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"


class Stories(BaseModel):
    title =models.CharField(verbose_name="title of stories" , max_length=50,help_text="max 50 characters")
    image = models.ImageField(upload_to="stories_img",verbose_name="Image of Stories")
    category = models.ForeignKey(Category,on_delete=models.CASCADE,verbose_name='Category of the blog',related_name="story_category")
    recipes = RichTextUploadingField()
    tag=models.ManyToManyField(Tag,related_name="story_tag")
    author = models.ForeignKey(CustomUser,on_delete=models.CASCADE,related_name='story_author')
    # user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='story_of_user')

    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name = "Story"
        verbose_name_plural = "Stories"

    def get_absolute_url(self):
        return reverse('profile',kwargs={'pk': self.author.pk})
    
        


class Comment(BaseModel):
    name =models.CharField(verbose_name="Name of Comment",max_length=20,help_text="max 20 character")
    email = models.EmailField(verbose_name="email of comment")
    message = models.TextField(verbose_name="Mesage of comment")
    story = models.ForeignKey(Stories,on_delete=models.CASCADE,related_name="story_comment",null=True, blank=True)

    def __str__(self):
        return self.name
    class Meta:
        verbose_name = "Comment"
        verbose_name_plural = "Comments"

story/forms.py
from django.forms import ModelForm,Form
from .models import Comment,Stories
from django import forms
class CommentForm(ModelForm):
    class Meta:
        model=Comment
        fields = ["name","email","message"]
        widgets = {
            "name":forms.TextInput(attrs={'placeholder':"Name",'class':"form-control"}),
            'email':forms.EmailInput(attrs={'placeholder':"Email address","class":"form-control"}),
            'message':forms.Textarea(attrs={'placeholder':"Message","class":"form-control"})
        }


class SearchForm(forms.Form):
    search =forms.CharField(required=True)


class CreateStoryForm(ModelForm):
    class Meta:
        model=Stories
        fields =["title","recipes",'category',"image","tag"]
        widgets = {
            "tag":forms.SelectMultiple(attrs= {'placeholder':"Name",'class':"form-control"}),
        }

story/views.py
from django.db.models.base import Model as Model
from django.db.models.query import QuerySet
from django.forms import BaseModelForm
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render,redirect
from .models import Stories,Category,Tag,Comment,CustomUser
from django.db.models import Count
from django.urls import reverse_lazy
from .forms import CommentForm,SearchForm,CreateStoryForm
from django.views.generic import CreateView,ListView,DetailView,FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages

def stories(request):
    category_filter = request.GET.get('category')
    if category_filter:
        all_stories = Stories.objects.filter(category__name=category_filter)
    else:
        all_stories = Stories.objects.all()
    context = {
        'all_stories' : all_stories,
    }
    return render(request, 'stories.html',context)

# def story(request,pk):
#     all_story = Stories.objects.get(pk=pk)
#     all_category= Category.objects.annotate(count = Count('story_category'))
#     all_tags = Tag.objects.all()
#     recent_blog = Stories.objects.order_by("created_at")[:3]
    

#     if request.method =="POST":
#         form=CommentForm(data=request.POST)
#         if form.is_valid():
#             storyform = form.save(commit=False)
#             storyform.story = all_story
#             storyform.save()
#             return redirect('story', pk=pk) 
#     else:
#             form = CommentForm()

#     context={
#         'all_story' : all_story,
#         'recent_blog':recent_blog,
#         'all_category':all_category,
#         'all_tags':all_tags,
#         'form':form,

#     }
#     return render(request, 'single.html',context)

class CreateStoryView(CreateView):
    template_name = "create_story.html"
    form_class = CreateStoryForm
    model = Stories 
    def get_context_data(self, **kwargs):
        context = super(CreateStoryView,self).get_context_data(**kwargs)
        context['tags'] = Tag.objects.all()
        return  context
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)




class RecipesView(ListView):
    template_name = "recipes.html"
    def get_queryset(self):
        category = self.request.GET.get('category')
        if category:
            return Stories.objects.filter(category__name = category).all()
        return Stories.objects.all()
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["recipes"] = Stories.objects.all()
        return context
       


class RecipesDetail(DetailView,FormView):
    template_name = "recipes-detail.html"
    model = Stories
    form_class = CommentForm
    context_object_name = "recipe"
    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        context['recents'] = Stories.objects.order_by('-created_at')[:3]
        context['tags'] = Tag.objects.all()
        return context
    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            recipeform = form.save(commit = False)
            recipeform.story = Stories.objects.get(pk=self.kwargs["pk"])
            recipeform.save()
            return redirect('recipe',pk=self.kwargs['pk'])
        else:
            form = CommentForm() 



   
    
    
   

class SearchView(FormView):
    template_name = "blog_search.html"
    form_class = SearchForm
    def form_valid(self, form):
        search_form = form.cleaned_data['search']
        search_data =  Stories.objects.filter(title__icontains=search_form)
        context = {
                'search_data':search_data,
            }
        return render(self.request, 'blog_search.html',context)
    def form_invalid(self):
        return redirect('stories')
        


# def blog_search(request):
#     if request.method == "POST":
#         form = SearchForm(data=request.POST)
#         if form.is_valid():
#             search_form = form.cleaned_data['search']
#             search_data =  Stories.objects.filter(title__icontains=search_form)
#             recipes_search =  Recipes.objects.filter(title__icontains=search_form)
#             print(recipes_search)
#             context ={
#                 'search_data':search_data,
#                 'recipes_search':recipes_search,
#             }
#             return render(request, 'blog_search.html',context)
#     return redirect('stories')
  


   

        

story/templates/create_recipe.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Create Story {% endblock %}

{% block content %}
    <section class="ftco-section contact-section create-story">
        <div class="container">
            <div class="row block-9 justify-content-center">
                <div class="col-md-6 order-md-last d-flex">
                    <form method="POST" class="bg-light p-5 contact-form" enctype="multipart/form-data">
                        {% csrf_token %}
                        <a class="navbar-brand center" href="#">Add New Recipe<span>.</span></a>
                        <div class="form-group">
                            <input name="title" type="text" class="form-control" placeholder="Title">
                        </div>
                        <div class="form-group">
                            <textarea name="descriptions" rows="10" class="form-control" placeholder="Description"></textarea>
                        </div>
                        <div class="form-group">
                            <select class="form-control mb-3" name="category" id="">
                                <option value="0">Select category</option>
                                {% for cat in category_list %}
                                    <option value="1">{{cat}}</option>
                                {% endfor %}
                            </select>
                            <select class="form-control mb-3" name="tag" id="">
                                <option value="0">Select tags</option>
                                {% for tag in tags %}
                                    <option value="1">{{tag}}</option>
                                {% endfor %}
                     
                                </select>
                        </div>
                        <div class="form-group">
                            <input name="image" type="file"  accept="image/png,image/gif,image/jpeg,image.jpg">
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Create" class="btn btn-primary py-3 px-5">
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </section>
{% endblock %}

story/templates/create_story.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Create Story {% endblock %}

{% block content %}
    <section class="ftco-section contact-section create-story">
        <div class="container">
            <div class="row block-9 justify-content-center">
                <div class="col-md-6 order-md-last d-flex">
                    <form method="POST" class="bg-light p-5 contact-form" enctype="multipart/form-data">
                        {% csrf_token %}
                        <a class="navbar-brand center" href="#">Add New Stories<span>.</span></a>
                        <div class="form-group">
                            <input name="title" type="text" class="form-control" placeholder="Title">
                        </div>
                        <div class="form-group">
                            <textarea name="recipes" rows="10" class="form-control" placeholder="Recipe"></textarea>
                        </div>
                        <div class="form-group">
                            <select class="form-control mb-3" name="category" id="">
                                <option value="0">Select category</option>
                                {% for cat in category_list %}
                                    <option value="1">{{cat}}</option>
                                {% endfor %}
                            </select>
                            <select class="form-control mb-3" name="tag" id="">
                                <option value="0">Select tags</option>
                                {% for tag in tags %}
                                    <option value="1">{{tag}}</option>
                                {% endfor %}
                     
                                </select>
                        </div>
                        <div class="form-group">
                            <input name="image" type="file"  accept="image/png,image/gif,image/jpeg,image.jpg">
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Create" class="btn btn-primary py-3 px-5">
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </section>
{% endblock %}

story/templates/recipes-detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Food Story {% endblock %}

{% block content %}
<section class="hero-wrap hero-wrap-2" style="background-image: url({% static 'images/bg_4.jpg' %});">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-center">
            <div class="col-md-9 ftco-animate pb-5 text-center">
                <h1 class="mb-3 bread">{{recipe.title}} </h1>
                <p class="breadcrumbs">
                    <span class="mr-2"><a href="{% url 'home' %}">Home <i class="ion-ios-arrow-forward"></i></a></span>
                    <span class="mr-2"><a href="{% url 'recipes' %}">Recipe Page <i
                                class="ion-ios-arrow-forward"></i></a></span>
                    <span>Detail Page<i class="ion-ios-arrow-forward"></i></span>
                </p>
            </div>
        </div>
    </div>
</section>

<section class="ftco-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 order-lg-last ftco-animate">
                <h1>{{recipe.title}} Recipe</h1>
                {{recipe.descriptions|safe}}
                <div class="tag-widget post-tag-container mb-5 mt-5">
                    <div class="tagcloud">
                        {% for tag in recipe.tag.all %}

                        <a href="#" class="tag-cloud-link">{{tag}}</a>
                        {% endfor %}
                    </div>
                </div>

                <div class="about-author d-flex p-4 bg-light">
                    <div class="bio mr-5">
                        {% if recipe.author.profile_photo %}
                        <img src="{{recipe.author.profile_photo.url}}" alt="Image placeholder"
                            class="img-fluid-author mb-4">
                        {% endif %}
                    </div>
                    <div class="desc">
                        <h3>{{recipe.author.first_name}} {{recipe.author.last_name}}</h3>
                        <p>{{recipe.author.about|safe}}</p>
                    </div>
                </div>


                <div class="pt-5 mt-5">
                    <h3 class="mb-5">{{recipe.story_comment.count}} Comments</h3>
                    <ul class="comment-list">
                        {% for comment in recipe.story_comment.all %}
                        <li class="comment">
                            <div class="vcard bio">
                                <img src="{% static 'images/blank_profile.png' %}" alt="Image placeholder">
                            </div>
                            <div class="comment-body">
                                <h3>{{comment.name}}</h3>
                                <div class="meta">{{comment.created_at}}</div>
                                <p>{{comment.message}}</p>
                                <p><a href="#" class="reply">Reply</a></p>
                            </div>
                        </li>
                        {% endfor %}


                        <div class="comment-form-wrap pt-5">
                            <h3 class="mb-5">Leave a comment</h3>
                            <form method="POST" class="p-5 bg-light">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="name">Name *</label>
                                    <input name="name" type="text" class="form-control" id="name">
                                </div>
                                <div class="form-group">
                                    <label for="email">Email *</label>
                                    <input name="email" type="email" class="form-control" id="email">
                                </div>
                                <div class="form-group">
                                    <label for="message">Message</label>
                                    <textarea name="message" id="message" cols="30" rows="10"
                                        class="form-control"></textarea>
                                </div>
                                <div class="form-group">
                                    <input type="submit" value="Post Comment" class="btn py-3 px-4 btn-primary">
                                </div>

                            </form>
                        </div>
                </div>

            </div> <!-- .col-md-8 -->
            <div class="col-lg-4 sidebar pr-lg-5 ftco-animate">

                <div class="sidebar-box ftco-animate">
                    <ul class="categories">
                        <h3 class="heading mb-4">Categories</h3>
                        {% for category in category_list %}
                        <li><a href="{% url 'recipes' %}?category={{category.name}}">{{category}}
                                <span>({{category.count}})</span></a></li>
                        {% endfor %}
                    </ul>
                </div>

                <div class="sidebar-box ftco-animate">
                    <h3 class="heading mb-4">Recent Blog</h3>
                    {% for recent in recents %}
                    <div class="block-21 mb-4 d-flex">
                        <a href="{% url 'recipe' recent.pk %}" class="blog-img mr-4"
                            style="background-image: url({{recent.image.url}})"></a>
                        <div class="text">
                            <h3><a href="{% url 'recipe' recent.pk %}">{{recent.title}}</a></h3>
                            <div class="meta">
                                <div><a href="#"><span class="icon-calendar"></span>
                                        {{recent.created_at|date:"d,M,Y"}}</a></div>
                                <div><a href="#"><span class="icon-person"></span> {{recipe.author}}</a></div>
                                <div><a href="#"><span class="icon-chat"></span> {{recent.story_comment.count}}</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}

                </div>

                <div class="sidebar-box ftco-animate">
                    <h3 class="heading mb-4">Tag Cloud</h3>
                    <div class="tagcloud">
                        {% for tag in tags %}
                        <a href="#" class="tag-cloud-link">{{tag.name}}</a>
                        {% endfor %}
                    </div>
                </div>
            </div>

        </div>
    </div>
</section> <!-- .section -->

<section class="ftco-subscribe ftco-section bg-light">
    <div class="overlay">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-md-8 text-wrap text-center heading-section ftco-animate">
                    <h2 class="mb-4"><span>Subcribe to our Newsletter</span></h2>
                    <p>A small river named Duden flows by their place and supplies it with the necessary regelialia. It
                        is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
                    <div class="row d-flex justify-content-center mt-4 mb-4">
                        <div class="col-md-8">
                            <form action="#" class="subscribe-form">
                                <div class="form-group d-flex">
                                    <input type="text" class="form-control" placeholder="Enter email address">
                                    <input type="submit" value="Subscribe" class="submit px-3">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

story/templates/recipes.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Recipes {% endblock %}

{% block content %}
    <section class="hero-wrap hero-wrap-2" style="background-image: url({% static 'images/bg_4.jpg' %});">
        <div class="overlay"></div>
        <div class="container">
            <div class="row no-gutters slider-text align-items-end justify-content-center">
                <div class="col-md-9 ftco-animate pb-5 text-center">
                    <h1 class="mb-3 bread">Recipes</h1>
                    <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home <i
                            class="ion-ios-arrow-forward"></i></a></span> <span>Recipes <i
                            class="ion-ios-arrow-forward"></i></span></p>
                </div>
            </div>
        </div>
    </section>

    <section class="ftco-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-9">
                    <div class="row">
                        {% for recipe in recipes %}
                        <div class="col-md-6 col-lg-12 ftco-animate">
                            <div class="blog-entry d-lg-flex">
                                <div class="half">
                                    <a href="single.html" class="img d-flex align-items-end"
                                    style="background-image: url({{recipe.image.url}});">
                                        <div class="overlay"></div>
                                    </a>
                                </div>
                                <div class="text px-md-4 px-lg-5 half pt-3">
                                    <p class="meta d-flex"><span class="pr-3">{{recipe.category}}</span><span class="ml-auto pl-3">{{recipe.created_at|date:"d,M,Y"}}</span>
                                    </p>
                                    <h3><a href="single.html">{{recipe.title}}</a></h3>
                                    <p>{{recipe.descriptions|safe|truncatechars:150}}
                                    </p>
                                    <p class="mb-0"><a href="{% url 'recipe' recipe.pk %}" class="btn btn-primary">Read More <span
                                            class="icon-arrow_forward ml-4"></span></a></p>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                       
                    </div>
                    <div class="row mt-5">
                        <div class="col text-center">
                            <div class="block-27">
                                <ul>
                                    <li><a href="#">&lt;</a></li>
                                    <li class="active"><span>1</span></li>
                                    <li><a href="#">2</a></li>
                                    <li><a href="#">3</a></li>
                                    <li><a href="#">4</a></li>
                                    <li><a href="#">5</a></li>
                                    <li><a href="#">&gt;</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-lg-3">
                    <div class="sidebar-wrap">
                        {% if user.is_authenticated %}
                        <div class="sidebar-box p-4 about text-center ftco-animate">
                            <h2 class="heading mb-4">About<br>{{user.first_name}} {{user.last_name}}</h2>
                            <img src="{% static 'images/author.jpg' %}" class="img-fluid" alt="Colorlib Template">
                            <div class="text pt-4">
                                <p>Hi! My name is <strong>{{user.first_name}} {{user.last_name}}</strong>, behind the word mountains, far from the
                                    countries Vokalia and Consonantia, there live the blind texts. Separated they live in
                                    Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
                            </div>
                        </div>
                        {% endif %}
                        <div class="sidebar-box p-4 ftco-animate">
                            <form method="POST"  action="/search/" class="search-form">
                                {% csrf_token %}
                                <div class="form-group">
                                    <span class="icon icon-search"></span>
                                    <input type="text" name="search" class="form-control" placeholder="Search">
                                    <button type="submit" class="icon icon-search p-2" style="border: none;"></button>

                                </div>
                            </form>
                        </div>
                        <div class="sidebar-box categories text-center ftco-animate">
                            <h2 class="heading mb-4">Categories</h2>
                            <ul class="category-image">
                                {% for category in category_list %}
                                <li>
                                    <a href="{% url 'recipes' %}?category={{category}}" class="img d-flex align-items-center justify-content-center text-center"
                                    style="background-image: url({{category.image.url}});">
                                        <div class="text">
                                            <h3>{{category.name}}</h3>
                                        </div>
                                    </a>
                                </li>
                                {% endfor %}
                               
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="ftco-subscribe ftco-section bg-light">
        <div class="overlay">
            <div class="container">
                <div class="row d-flex justify-content-center">
                    <div class="col-md-8 text-wrap text-center heading-section ftco-animate">
                        <h2 class="mb-4"><span>Subcribe to our Newsletter</span></h2>
                        <p>A small river named Duden flows by their place and supplies it with the necessary regelialia. It
                            is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
                        <div class="row d-flex justify-content-center mt-4 mb-4">
                            <div class="col-md-8">
                                <form action="#" class="subscribe-form">
                                    <div class="form-group d-flex">
                                        <input type="text" class="form-control" placeholder="Enter email address">
                                        <input type="submit" value="Subscribe" class="submit px-3">
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}